[package]
name = "iw_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
actix-multipart = "0.4"
actix-cors = "0.6"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
sanitize-filename = "0.5"
lopdf = "0.27"
printpdf = "0.5.0"
regex = "1"
tempfile = "3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"